title = "Workload example"

[global]
block_size = 5
Duration = "160s"
server="192.168.206.46"
port="8081"
IgnoreAttrs=["__name", "__size", "__atime_secs", "__mtime_secs", "__ctime_secs", "__atime_nsecs",
             		"__mtime_nsecs", "__ctime_nsecs", "__inode_number", "__obj_type", "__collection_id",
             		"__tiny_low", "__tiny_high", "__uid", "__gid", "__mode"]
TLSMode=false
 [global.StatusCodesAcceptance]
  200 = 100.0 # upto 100% return status of 200
  204 = 100.0
  205 = 100.0

[workloads]
   [workloads.line2kv]
   name="line2kv example"
   Generator="restore"
   Container="1"
   Target=""
   workers=20
   payload="get_items.Big data.4.0"
   schema="Big data.data.json"






