title = "Workload put example"

[global]
block_size = 5
Duration = "160s"
server="127.0.0.1"
port="8080"
TLSMode=false
 [global.StatusCodesAcceptance]
  200 = 100.0
  204 = 100.0
  205 = 100.0

[workloads]
   [workloads.put]
    generator="performance"
    name="10 seconds put from 20 workers"
    bucket=""
    Target="test.html"
    Duration = "10s"
    TYPE="PUT"
    workers=20
    count=10
