title = "Workload putappend example"

[global]
block_size = 5
Duration = "160s"
server="127.0.0.1"
port="8080"
TLSMode=false
[global.StatusCodesAcceptance]
   200 = 100.0
   204 = 100.0
   205 = 100.0

[workloads]
   [workloads.putappend]
   name="10 seconds putappend from 5 workers"
   bucket=""
   Target="test.html"
   Duration = "10s"
   TYPE="PUT"
   workers=5
   count=0
   [workloads.putappend.Header]
      range = "-1"
